Cart/urls.py
from django.conf.urls import url

from Cart import views

urlpatterns=[
    url(r'^marketPlus/',views.marketPlus),
    url(r'^marketReduce/',views.marketReduce),
    url(r'^changeStatus/',views.changeStatus),
    url(r'^changeAll/',views.changeAll),
]

User/urls.py
from django.conf.urls import url

from User import views

urlpatterns = [
    url(r'^login', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    url(r'^checkCode', views.checkCode, name='checkCode'),
    url(r'^checkUser', views.checkUser, name='checkUser'),
    url(r'^sende_mail', views.sende_mail),
    url(r'^logout', views.logout,name='logout'),
]

yixianshengApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^yxshome/', include('Home.urls', namespace='yxshome')),
    url(r'^user/',include('User.urls',namespace='user')),
    url(r'^cart/',include('Cart.urls',namespace='cart')),
    url(r'^order/',include('Order.urls',namespace='order')),
    url(r'^', include('Market.urls')),
]

templates/yiXianSheng/main/mine/mine.html
{% extends "base_home.html" %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'yiXianSheng/main/mine/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'yiXianSheng/main/mine/js/mine.js' %}"></script>
{% endblock %}

{% block title %}
{{ block.super }}
    我的
{% endblock %}

{% block content %}
    {{ block.super }}
    <div id="mine">
        <div class="fixed">
            <span>
                {% if myuser %}
                    <img src="/static/upload/{{ myuser.u_icon }}" alt="">
                    {% else %}
                    <span class="glyphicon glyphicon-user"></span>
                {% endif %}
            </span>
            {% if myuser %}
                <p>
                    {{ myuser.u_name }}
                </p>
                {% else %}
                <div id="regis">
                    注册
                </div>
                <p id="tologin">
                    未登录
                </p>
            {% endif %}
            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级:0</span>
            </p>
            <p>
                <span class="glyphicon glyphicon-heart"></span>
                商品收藏
            </p>
        </div>

        <div class="mine">
            <p>
                <span>全部订单</span>
                <span><a href="">全部订单 》</a></span>
            </p>
            <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>
                                待付款
                            </dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </div>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服反馈</dd>
                        </dl>
                    </li>

                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if myuser %}
                <p><a href="{% url 'user:logout' %}">退出</a></p>
            {% endif %}

        </div>
    </div>
{% endblock %}