Cart/urls.py
from django.conf.urls import url

from Cart import views

urlpatterns=[
    url(r'^marketPlus/',views.marketPlus),
    url(r'^marketReduce/',views.marketReduce),
    url(r'^changeStatus/',views.changeStatus),
    url(r'^changeAll/',views.changeAll),
]

Home/urls.py
from django.conf.urls import url

from Home import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^market/', views.market, name='market'),
    url(r'^mine/', views.mine, name='mine'),

]

yixianshengApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^yxshome/', include('Home.urls', namespace='yxshome')),
    url(r'^user/',include('User.urls',namespace='user')),
    url(r'^cart/',include('Cart.urls',namespace='cart')),
    url(r'^order/',include('Order.urls',namespace='order')),
    url(r'^', include('Market.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>
    {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    {% block ext_css %}{% endblock %}
</head>
<body>

{% block headers %}{% endblock %}

{% block content %}{% endblock %}

{% block footer %}{% endblock %}


<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>

{% block ext_js %}{% endblock %}
</body>
</html>

templates/base_home.html
{% extends "base.html" %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'yiXianSheng/main/css/main.css' %}">
{% endblock %}

{% block headers %}
    {{ block.super }}
    <header></header>

{% endblock %}

{% block footer %}
    {{ block.super }}
    <footer>
        <a href="{% url 'yxshome:home' %}">
            <dl class="home">
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>

        <a href="{% url 'yxshome:market' %}">
            <dl class="market">
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>

        <a href="{% url 'yxshome:cart' %}">
            <dl class="cart">
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>

        <a href="{% url 'yxshome:mine' %}">
            <dl class="mine">
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}


templates/base_pay.html
{% extends "base.html" %}
{% load static %}

{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'yiXianSheng/pay/css/order.css' %}">
{% endblock %}

{% block headers %}
    {{ block.super }}
    <header></header>
{% endblock %}

templates/base_user.html
{% extends "base.html" %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'yiXianSheng/user/css/user.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'yiXianSheng/user/js/jiami.js' %}"></script>
{% endblock %}

{% block headers %}
    {{ block.super }}
    <header></header>

{% endblock %}