Cart/urls.py
from django.conf.urls import url

from Cart import views

urlpatterns=[
    url(r'^marketPlus/',views.marketPlus),
    url(r'^marketReduce/',views.marketReduce),
    url(r'^changeStatus/',views.changeStatus),
    url(r'^changeAll/',views.changeAll),
]

User/urls.py
from django.conf.urls import url

from User import views

urlpatterns = [
    url(r'^login', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    url(r'^checkCode', views.checkCode, name='checkCode'),
    url(r'^checkUser', views.checkUser, name='checkUser'),
    url(r'^sende_mail', views.sende_mail),
    url(r'^logout', views.logout,name='logout'),
]

yixianshengApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^yxshome/', include('Home.urls', namespace='yxshome')),
    url(r'^user/',include('User.urls',namespace='user')),
    url(r'^cart/',include('Cart.urls',namespace='cart')),
    url(r'^order/',include('Order.urls',namespace='order')),
    url(r'^', include('Market.urls')),
]

User/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    u_name=models.CharField(max_length=32)
    u_password=models.CharField(max_length=128)
    u_mail=models.CharField(max_length=32)
    u_icon=models.ImageField(upload_to='icons')
    u_tokon=models.CharField(max_length=128)
    u_active=models.BooleanField(default=False)

    class meta():
        db_table='users'

User/views.py
import uuid

from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from PIL import Image, ImageDraw, ImageFont, ImageFilter
import random, string, io

# Create your views here.
from django.urls import reverse

from User.models import Users
from User.userHelp import makeEncryption, checkPsd, sendemail
from yixianshengApp import settings


def checkCode(request):
    # 背景颜色
    bgcolor = (random.randrange(10, 255), random.randrange(50, 160), 255)

    # 宽高
    width = 100
    height = 50

    # 创建画板
    img = Image.new(mode='RGB', size=(width, height), color=bgcolor)

    # 创建画笔
    draw = ImageDraw.Draw(img, mode='RGB')

    for i in range(200):
        fill = (random.randrange(256), random.randrange(256), random.randrange(256))
        xy = (random.randrange(100), random.randrange(50))
        draw.point(xy=xy, fill=fill)

    # 定义字符
    text = string.digits + string.ascii_letters
    font1 = ImageFont.truetype(settings.FONT_PATH, 30)

    code = ''
    for i in range(4):
        code1 = text[random.randrange(0, len(text))]
        code += code1
        color1 = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        draw.text((i * 24, i * 6), code1, color1, font1)

        # 干扰线
        linecolor = (random.randrange(1, 255), random.randrange(1, 255), random.randrange(1, 255))
        for i in range(2):
            begin = (random.randint(0, width), random.randint(0, height))
            end = (random.randint(0, width), random.randint(0, height))
            draw.line([begin, end], fill=linecolor)

    # img = img.transform((width + 20, height + 10), Image.AFFINE, (1, -0.3, 0, -0.1, 1, 0), Image.BILINEAR)
    img = img.filter(ImageFilter.EDGE_ENHANCE_MORE)

    buf = io.BytesIO()
    img.save(buf, 'png')
    request.session['code'] = code

    return HttpResponse(buf.getvalue(), 'image/png')


def login(request):
    if request.method=='POST':
        code=request.POST.get('u_code')
        checkcode=request.session.get('code')
        if code.lower() == checkcode.lower():
            username=request.POST.get('name')
            user=Users.objects.filter(u_name=username)
            if user.exists():
                password=request.POST.get('password')
                old_psd=user[0].u_password
                if checkPsd(password,old_psd,username):
                    if user[0].u_active:
                        request.session['uid']=user[0].id
                        return redirect(reverse('yxshome:mine'))
                    else:
                        return render(request, 'yiXianSheng/user/login.html', {'erro': '该用户未激活账户!!!'})
                else:
                    return render(request, 'yiXianSheng/user/login.html', {'erro': '密码不正确!!!'})
            else:
                return render(request, 'yiXianSheng/user/login.html', {'erro': '用户名不存在!!!'})
        else:
            return render(request, 'yiXianSheng/user/login.html',{'erro':'验证码错误!!!'})
    else:
        return render(request, 'yiXianSheng/user/login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        icon = request.FILES.get('icon')
        newPsd = makeEncryption(password, username)
        token = uuid.uuid4()
        user = Users(
            u_name=username,
            u_password=newPsd,
            u_mail=email,
            u_icon=icon,
            u_tokon=token
        )
        user.save()

        sendemail(username, email, token)

        cache.set(token, user.id, timeout=30)

        return redirect(reverse('user:login'))

    else:
        return render(request, 'yiXianSheng/user/register.html')


def checkUser(request):
    data = request.POST.get('username')
    user = Users.objects.filter(u_name=data)
    if user:
        msg = {'data': True}
    else:
        msg = {'data': False}
    return JsonResponse(msg)


def sende_mail(request):
    token = request.GET.get('token')
    uid=cache.get(token)

    if uid:
        user=Users.objects.get(pk=uid)
        user.u_active=True
        user.save()

        cache.delete(token)
        return HttpResponse('激活成功')
    else:
        return HttpResponse('邮件已过期，请重新激活')


def logout(request):
    request.session.delete()
    return render(request , 'yiXianSheng/main/mine/mine.html')

templates/yiXianSheng/user/email.html
<h3>尊敬的{{ name }}您好：</h3>
<pre>
    欢迎注册XXX用户，请点击下方链接进行激活账户。
激活链接：<span style="font-style: italic"><a href="{{ url }}">{{ url }}</a></span>。

</pre>

templates/yiXianSheng/user/login.html
{% extends "base_user.html" %}
{% load static %}

{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static '/yiXianSheng/user/login/css/login.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static '/yiXianSheng/user/login/js/login.js' %}"></script>
{% endblock %}


{% block title %}
{{ block.super }}
    登录
{% endblock %}

{% block content %}
    {{ block.super }}
    <div id="login">


        <span style="color: #70e81c" id="log_back"  class="btn">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </span>

        <div class="container">
            <span>{{ erro }}</span>
            <form action="{% url 'user:login' %}" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input name="name" type="text" class="form-control" id="exampleName" placeholder="请输入用户名">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" name="password" class="form-control" id="examplePassword" placeholder="请输入密码">
                </div>

                <img src="/user/checkCode/" alt="#" id="i_code">
                <div class="form-group">
                    <label for="exampleInputFile">验证码</label>
                    <input type="text" name="u_code" class="form-control" placeholder="请输入验证码">
                </div>

                <button type="submit" class="btn btn-block btn-info">登录</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/yiXianSheng/user/register.html
{% extends "base_user.html" %}
{% load static %}

{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static '/yiXianSheng/user/register/css/register.css' %}">
{% endblock %}

{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static '/yiXianSheng/user/register/js/myRegister.js' %}"></script>
{% endblock %}

{% block title %}
{{ block.super }}
    注册
{% endblock %}

{% block content %}
    {{ block.super }}
    <div id="register">
        <div class="error"></div>
        <span style="color: #70e81c" id="res_back" class="btn">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </span>
        <div class="container">
            <form action="{% url 'user:register' %}" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                    <span id="span_user" class="bg-warning" style="font-size: 3px;color: #999999;"></span>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" name="password" placeholder="请输入密码">
                    <span id="span_psd1" class="bg-warning" style="font-size: 3px;color: #999999;"></span>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_again" placeholder="请再次输入密码">
                    <span id="span_psd2" class="bg-warning" style="font-size: 3px;color: #999999;"></span>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" name="email" placeholder="请输入邮箱">
                    <span id="span_email" class="bg-warning" style="font-size: 3px;color: #999999;"></span>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">头像</label>
                    <input type="file" name="icon" class="btn text-info" style="border: none">
                </div>

                <button type="submit" class="btn btn-block btn-primary">注册</button>
            </form>
        </div>
    </div>
{% endblock %}